name: Convert ZIP to TAR.GZ and Store in Artifacts

on:
  workflow_dispatch:  # اجرای دستی از GitHub Actions

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest release ZIP files
        run: |
          mkdir -p release_files
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/Angize/3x-ui/releases/latest | jq -r '.tag_name')

          if [ "$LATEST_RELEASE" = "null" ]; then
            echo "No latest release found!"
            exit 1
          fi
          
          ZIP_URLS=$(curl -s https://api.github.com/repos/Angize/3x-ui/releases/latest | jq -r '.assets[] | select(.name | endswith(".zip")) | .browser_download_url')

          if [ -z "$ZIP_URLS" ]; then
            echo "No ZIP files found in latest release!"
            exit 1
          fi
          
          for url in $ZIP_URLS; do
            wget -P release_files "$url"
          done

      - name: Check available disk space
        run: df -h

      - name: Convert Each ZIP File to TAR.GZ Separately
        run: |
          mkdir -p converted_files
          for file in release_files/*.zip; do
            echo "Processing $file..."
            extract_dir="extracted_$(basename "$file" .zip)"
            unzip "$file" -d "$extract_dir" || { echo "Error extracting $file"; exit 1; }
            tar_filename="$(basename "$file" .zip).tar.gz"
            tar -czvf "converted_files/$tar_filename" "$extract_dir"
            rm -r "$extract_dir"
          done

      - name: Upload Each TAR.GZ File Separately to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-tar-files
          path: converted_files/
