name: Convert Each ZIP to TAR.GZ

on:
  workflow_dispatch:  # اجرای دستی از GitHub Actions

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest release ZIP files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir release_files
          gh release download --pattern "*.zip" --dir release_files || { echo "No ZIP files found in Releases!"; exit 1; }

      - name: Check available disk space
        run: df -h

      - name: Convert Each ZIP File to TAR.GZ Separately
        run: |
          mkdir converted_files
          for file in release_files/*.zip; do
            echo "Processing $file..."
            extract_dir="extracted_$(basename "$file" .zip)"
            unzip "$file" -d "$extract_dir" || { echo "Error extracting $file"; exit 1; }
            tar_filename="$(basename "$file" .zip).tar.gz"
            tar -czvf "converted_files/$tar_filename" "$extract_dir"
            rm -r "$extract_dir"
          done

      - name: Upload Each TAR.GZ File Separately
        run: |
          for file in converted_files/*.tar.gz; do
            filename=$(basename "$file")
            echo "Uploading $filename..."
            gh release upload latest "$file" --clobber
          done
